DROP TRIGGER phase6_forward_evaluation_exact_source;
CREATE TRIGGER phase6_forward_evaluation_exact_source BEFORE INSERT ON phase6_forward_evaluation_races
WHEN NOT EXISTS (
  SELECT 1 FROM canonical_training_examples c
  JOIN training_examples t ON t.training_example_id=c.phase3_training_example_id
  JOIN races r ON r.race_id=c.race_id
  WHERE c.training_example_id=NEW.training_example_id AND c.race_id=NEW.race_id
    AND c.evidence_checksum=NEW.evidence_checksum AND c.result_checksum=NEW.result_checksum
    AND c.racing_date=NEW.racing_day AND c.artifact_checksum=NEW.training_artifact_checksum
    AND t.eligibility='eligible' AND r.state='training_example_ready'
    AND (SELECT count(*) FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='venue')=1
    AND (SELECT json_extract(f.value_json,'$') FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='venue')=NEW.venue
    AND (SELECT count(*) FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='distance')=1
    AND (SELECT CAST(json_extract(f.value_json,'$') AS INTEGER) FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='distance')=NEW.distance_m
    AND (SELECT count(*) FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='grade')=1
    AND (SELECT json_extract(f.value_json,'$') FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='grade')=NEW.grade
    AND (SELECT count(*) FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='field_size')=1
    AND (SELECT CAST(json_extract(f.value_json,'$') AS INTEGER) FROM field_evidence f WHERE f.race_id=NEW.race_id AND f.field_name='field_size')=NEW.field_size
)
BEGIN SELECT RAISE(ABORT,'forward evaluation race lacks unambiguous eligible Phase-5 source'); END;

CREATE TABLE phase6_bundle_run_provenance (
  bundle_id TEXT PRIMARY KEY REFERENCES canonical_model_bundles(bundle_id),
  registration_run_id TEXT NOT NULL REFERENCES phase6_runs(run_id),
  source_run_id TEXT NOT NULL REFERENCES phase6_runs(run_id),
  operation_id TEXT NOT NULL UNIQUE REFERENCES operations(operation_id),
  CHECK(registration_run_id<>source_run_id)
);

CREATE TABLE phase6_forecast_service_artifacts (
  forecast_checksum TEXT PRIMARY KEY,
  race_id TEXT NOT NULL,
  bundle_id TEXT NOT NULL REFERENCES canonical_model_bundles(bundle_id),
  bundle_checksum TEXT NOT NULL,
  evidence_checksum TEXT NOT NULL,
  artifact_checksum TEXT NOT NULL UNIQUE,
  generated_at TEXT NOT NULL,
  service_run_id TEXT NOT NULL REFERENCES phase6_runs(run_id),
  deferred_prediction_id TEXT REFERENCES deferred_predictions(prediction_id),
  operation_id TEXT NOT NULL UNIQUE REFERENCES operations(operation_id),
  FOREIGN KEY(bundle_id,bundle_checksum) REFERENCES canonical_model_bundles(bundle_id,bundle_checksum)
);

CREATE TABLE phase6_race_start_authority (
  race_id TEXT PRIMARY KEY REFERENCES races(race_id),
  scheduled_start_at TEXT NOT NULL,
  programme_checksum TEXT NOT NULL,
  operation_id TEXT NOT NULL UNIQUE REFERENCES operations(operation_id)
);

CREATE TABLE phase6_assignment_history (
  history_id TEXT PRIMARY KEY,
  effective_racing_day_id TEXT NOT NULL REFERENCES phase6_racing_day_schedule(racing_day_id),
  assignment_id TEXT NOT NULL REFERENCES canonical_serving_assignments(assignment_id),
  action TEXT NOT NULL CHECK(action IN ('promoted','rollback_restored')),
  prior_history_id TEXT REFERENCES phase6_assignment_history(history_id),
  recorded_at TEXT NOT NULL,
  operation_id TEXT NOT NULL UNIQUE REFERENCES operations(operation_id)
);

CREATE TABLE phase6_service_training_requests (
  training_request_id TEXT PRIMARY KEY REFERENCES phase6_training_requests(training_request_id),
  service_run_id TEXT NOT NULL REFERENCES phase6_runs(run_id),
  endpoint TEXT NOT NULL CHECK(endpoint='canonical_forecast_service'),
  operation_id TEXT NOT NULL UNIQUE REFERENCES operations(operation_id)
);

CREATE TRIGGER phase6_forecast_service_before_result BEFORE INSERT ON phase6_forecast_service_artifacts
WHEN NOT EXISTS (
 SELECT 1 FROM phase6_runs s JOIN phase6_race_start_authority a ON a.race_id=NEW.race_id
 WHERE s.run_id=NEW.service_run_id AND s.run_kind='forecast_service'
   AND s.started_at=NEW.generated_at AND NEW.generated_at<a.scheduled_start_at
   AND NOT EXISTS (SELECT 1 FROM result_attempts x WHERE x.race_id=NEW.race_id AND x.attempted_at<=NEW.generated_at)
)
BEGIN SELECT RAISE(ABORT,'forecast was not generated by the pre-result service boundary'); END;

CREATE TRIGGER phase6_bundle_run_exact_kinds BEFORE INSERT ON phase6_bundle_run_provenance
WHEN NOT EXISTS (SELECT 1 FROM phase6_runs r WHERE r.run_id=NEW.registration_run_id AND r.run_kind='registration')
 OR NOT EXISTS (SELECT 1 FROM phase6_runs r WHERE r.run_id=NEW.source_run_id AND r.run_kind IN ('training','tuning'))
BEGIN SELECT RAISE(ABORT,'bundle run provenance is incomplete'); END;

CREATE TRIGGER phase6_probation_auth_exact_day BEFORE INSERT ON phase6_probation_day_auth
WHEN NOT EXISTS (
 SELECT 1 FROM phase6_probation_days d JOIN phase6_racing_day_schedule s ON s.racing_day_id=NEW.racing_day_id
 JOIN racing_days r ON r.racing_day_id=s.racing_day_id
 WHERE d.probation_id=NEW.probation_id AND d.racing_day=r.local_date
   AND s.programme_checksum=NEW.programme_checksum
)
BEGIN SELECT RAISE(ABORT,'probation day identity or programme disagrees'); END;

CREATE TRIGGER phase6_bundle_run_append_only_update BEFORE UPDATE ON phase6_bundle_run_provenance BEGIN SELECT RAISE(ABORT,'bundle run provenance is append-only'); END;
CREATE TRIGGER phase6_bundle_run_append_only_delete BEFORE DELETE ON phase6_bundle_run_provenance BEGIN SELECT RAISE(ABORT,'bundle run provenance is append-only'); END;
CREATE TRIGGER phase6_service_forecast_append_only_update BEFORE UPDATE ON phase6_forecast_service_artifacts BEGIN SELECT RAISE(ABORT,'service forecasts are append-only'); END;
CREATE TRIGGER phase6_service_forecast_append_only_delete BEFORE DELETE ON phase6_forecast_service_artifacts BEGIN SELECT RAISE(ABORT,'service forecasts are append-only'); END;
CREATE TRIGGER phase6_race_start_append_only_update BEFORE UPDATE ON phase6_race_start_authority BEGIN SELECT RAISE(ABORT,'race starts are append-only'); END;
CREATE TRIGGER phase6_race_start_append_only_delete BEFORE DELETE ON phase6_race_start_authority BEGIN SELECT RAISE(ABORT,'race starts are append-only'); END;
CREATE TRIGGER phase6_assignment_history_append_only_update BEFORE UPDATE ON phase6_assignment_history BEGIN SELECT RAISE(ABORT,'assignment history is append-only'); END;
CREATE TRIGGER phase6_assignment_history_append_only_delete BEFORE DELETE ON phase6_assignment_history BEGIN SELECT RAISE(ABORT,'assignment history is append-only'); END;
