name: hardening-guard

on:
  push:
  pull_request:

jobs:
  hardening:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Compile project (syntax check)
        run: |
          python -m compileall -q .

      - name: Run hardening guard
        run: |
          python scripts/ci/check_hardening_guards.py

